language: objective-c
osx_image: xcode9.2

branches:
  only:
    - master
env:
  - LC_CTYPE=en_US.UTF-8 LANG=en_US.UTF-8
before_install:
  - rvm install ruby-2.2.2
  - gem install cocoapods
  - gem install xcpretty -N
  - brew update
script:
  - xcodebuild -workspace Example/EFIntroVideoViewController.xcworkspace -scheme EFIntroVideoViewController-Example -sdk iphonesimulator ONLY_ACTIVE_ARCH=NO | xcpretty -c
